name: flutter_gizi_anak
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  freezed_annotation: ^2.2.0
  meta: ^1.8.0
  intl: ^0.17.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_core: ^2.9.0
  flutter_easyloading: ^3.0.5
  dropdown_button2: ^1.8.0
  image_picker: ^0.8.7+2
  firebase_storage: ^11.1.0
  horizontal_data_table: 4.1.2+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flutter_launcher_icons: ^0.11.0

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/logo.png
  ios: true
  min_sdk_android: 21

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/